"""added_mcpconnection_model_oauth_updates

Revision ID: 6284a96c67f2
Revises: 92b1b00c9339
Create Date: 2026-06-07 10:43:14.906720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6284a96c67f2'
down_revision: Union[str, Sequence[str], None] = '92b1b00c9339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_connections', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('mcp_connections', sa.Column('credential_provider', sa.String(length=50), nullable=True))
    op.add_column('mcp_connections', sa.Column('encrypted_credentials', sa.String(), nullable=True))
    op.add_column('mcp_connections', sa.Column('oauth_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('mcp_connections', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mcp_connections', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('mcp_connections_nango_connection_id_key'), 'mcp_connections', type_='unique')
    op.drop_column('mcp_connections', 'allowed_tools')
    op.drop_column('mcp_connections', 'nango_connection_id')
    op.drop_column('mcp_connections', 'sync_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_connections', sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('mcp_connections', sa.Column('nango_connection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('mcp_connections', sa.Column('allowed_tools', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('mcp_connections_nango_connection_id_key'), 'mcp_connections', ['nango_connection_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('mcp_connections', 'last_used_at')
    op.drop_column('mcp_connections', 'token_expires_at')
    op.drop_column('mcp_connections', 'oauth_scopes')
    op.drop_column('mcp_connections', 'encrypted_credentials')
    op.drop_column('mcp_connections', 'credential_provider')
    op.drop_column('mcp_connections', 'display_name')
    # ### end Alembic commands ###
