"""added_apikeyregistry_model_last_used_at_field

Revision ID: 92b1b00c9339
Revises: 3c1888cb888f
Create Date: 2026-05-30 12:59:09.189991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b1b00c9339'
down_revision: Union[str, Sequence[str], None] = '3c1888cb888f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key_registry', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key_registry', 'last_used_at')
    # ### end Alembic commands ###
