"""add_document_processing_fields

Revision ID: baf0ad41f5d5
Revises: 6284a96c67f2
Create Date: 2026-08-02 12:54:12.762827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf0ad41f5d5'
down_revision: Union[str, Sequence[str], None] = '6284a96c67f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('total_chunks', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('error_detail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_detail')
    op.drop_column('documents', 'indexed_at')
    op.drop_column('documents', 'total_chunks')
    op.drop_column('documents', 'category')
    # ### end Alembic commands ###
